#!/usr/bin/env bash
#a program that displays "Best School" on the 4th loop it prints "bad luck" on the 8t iteratiom it prints "good luck"
N=1
while [[ $N -le 10 ]];
do
	if [ $N -eq 4 ]
	then
		echo "Bad luck"
	elif [ $N -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( N++ ))
done
