#!/usr/bin/env bash
#printing "Best School" 10 times using while loop
N=1
while [[ $N -le 10 ]];
do
	if [ $N -eq 4 ]
	then
		echo "Bad luck"
	elif [ $N -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( N++ ))
done
