#!/usr/bin/env bash
#this program prints 1-20, on the 5th iteration it prints bad luck from china, on the 10
i=1
while [ "$i" -le 20 ]
do
	echo "$i"
	case $i in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	(( i++ ))
done
